# vi: set ft=ruby :
source 'https://api.berkshelf.com'

metadata

# temporary until merged in to community cookbook
cookbook 'consul', git: 'git@github.com:romesh-mccullough/consul-cookbook.git', branch: "set-bind-interface"
